### ISSUE TITLE
Use createImmutable($this->path); instead

### ISSUE THREAD

**Issue by amineabri** [Skazzino/wordpress-modular-plugin#1]
https://github.com/Skazzino/wordpress-modular-plugin/blob/547040549678f344292f88613e12f68a60df4804/src/Environment/Adapters/DotAdapter.php#L20

$dotenv = Dotenv::createImmutable($this->path);

**Comment by Skazza94** [comment]
Hi @amineabri,
the `createImmutable` method is available in newer versions of phpdotenv. However, I'm stick to v2 for compatibility with PHP5.6. 
If I'll update the core and deprecate support for PHP5, I'll consider to switch to this new method.

However, thanks for the suggestion 😄
